// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etinzvnbkxcixptkoqvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0aW56dm5ia3hjaXhwdGtvcXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzM4ODIsImV4cCI6MjA3MDEwOTg4Mn0.34JozibeGMRWUvPhtbvW6J63YXHL0uuhX-gffB15Jy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});